apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: manikant2869/selfproject:latest
        ports:
        - containerPort: 3306
        env:
        - name: Database
          value: selfProject
        - name: DB_HOST
          value: database
---
apiVersion: v1
kind: Service
metadata:
  name: backendsvc
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3306


    